### ISSUE TITLE
Simplify development environment setup

### ISSUE THREAD

**Issue by rhoegg** [swu06/HSoftwareChallenge#1]
It took some effort to get the software into my local development environment and running.  I've recorded my steps below.

Is this the preferred method?  If so, we should update the README to include these steps.  If not, what is the preferred method?
1. Install Eclipse and create a workspace
2. Create a new project
3. Import -> File System -> select all items from the root of the repository
4. Import -> File System -> select all items from the `src` directory, choose target `src`
5. Update project to use latest JDK

**Comment by swu06** [comment]
Hi Ryan!

Sorry, I overlooked the install steps. I will outline them today and get
back to you.

Regards,
Sarah

**Comment by swu06** [comment]
Hi Ryan,

This difficulty was due to an oversight on my part- I failed to include the .project file so that Eclipse could import the git repository easily.  I have corrected this and updated the README file to include the full steps for getting a development setup going using Eclipse and Git.  It is much simpler now.

Sorry for the confusion and please let me know if you would like similar instructions for any other dev setups, building deployable jars, or other real-world tasks.

Regards,
Sarah

**Comment by swu06** [comment]
Closing Issue:  Resolved by adding in the necessary .project file and updating the README to include the necessary dev instructions.
